import React from "react";
import styles from "/styles/header.module.css"
import Head from "next/head";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faBars, faEnvelope, faUser } from "@fortawesome/free-solid-svg-icons";
import Image from "next/image";


const Header = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Company Name</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.header}>
        <FontAwesomeIcon
          className={styles.icon}
          icon={faBars}
          style={{ fontSize: 32, color: "white" }}
        />

        <div className={styles.logo}>
          <Image
            src="/EasyHandler_Hitam.png"
            alt="logo"
            width={50}
            height={50}
          />
        </div>
        <div className={styles.headerRight}>
          <FontAwesomeIcon
            className={styles.icon2}
            icon={faEnvelope}
            style={{ fontSize: 29, color: "white" }}
          />
          <FontAwesomeIcon
            className={styles.icon2}
            icon={faUser}
            style={{ fontSize: 29, color: "white" }}
          />
        </div>
      </div>
    </div>
  );
};

export default Header
