import React from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "/styles/Component/Navbar.module.css";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faBars, faEnvelope, faUser } from "@fortawesome/free-solid-svg-icons";
import Sidebar from "./sidebar";

export default function Navbar() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Company Name</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <nav className={`${styles.navbar}`}>
          <ul className={`${styles.navList}`}>
            <li className={styles.navItem}>
              <a type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasScrolling" aria-controls="offcanvasScrolling">
                <FontAwesomeIcon className={styles.icon} icon={faBars} style={{ fontSize: 32, color: "white" }} />
              </a>
            </li>
            <li className={styles.navItem}>
              <Image className={styles.imageLogo} src="/EasyHandler_Hitam.png" alt="logo" width={42} height={42} />
            </li>
            <li className={styles.navItem}>
              <button type="button" className= {`${styles["user-navbar"]} btn position-relative`}>
                <FontAwesomeIcon className={`${styles.navIcon}`} icon={faEnvelope} />
                <span className={`${styles["message"]} translate-middle badge`}>
                  99+
                  <span class="visually-hidden">unread messages</span>
                </span>
              </button>

              {/* <button type="button" class="btn btn-primary position-relative"> */}
              {/* <FontAwesomeIcon className={`${styles.navIcon}`} icon={faEnvelope} /> */}
              {/* <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger" />
                99+
                <span class="visually-hidden">unread messages</span>
              </button> */}
            </li>
            <li className={styles.navItem}>
              <div class="dropdown">
                <button className={`${styles["user-navbar"]} dropdown-toggle`} type="button" data-bs-toggle="dropdown" aria-expanded="false">
                  <FontAwesomeIcon className={`${styles.navIcon}`} icon={faUser} />
                </button>
                <ul class="dropdown-menu">
                  <li>
                    <Link href="#">
                      <a class="dropdown-item">Settings</a>
                    </Link>
                  </li>
                  <li>
                    <a class="dropdown-item" href="#">
                      Another action
                    </a>
                  </li>
                  <li>
                    <a class="dropdown-item" href="#">
                      Something else here
                    </a>
                  </li>
                </ul>
              </div>
            </li>
          </ul>
        </nav>
        {/* <div className={styles.header}>
					<a
						type="button"
						data-bs-toggle="offcanvas"
						data-bs-target="#offcanvasScrolling"
						aria-controls="offcanvasScrolling"
					>
						<FontAwesomeIcon
							className={styles.icon}
							icon={faBars}
							style={{ fontSize: 32, color: "white" }}
						/>
					</a>
					<div className={styles.logo}>
						<Image src="/EasyHandler_Hitam.png" alt="logo" width={50} height={50} />
					</div>
					<div className={styles.headerRight}>
						<FontAwesomeIcon
							className={styles.icon2}
							icon={faEnvelope}
							style={{ fontSize: 29, color: "white" }}
						/>
						<FontAwesomeIcon
							className={styles.icon2}
							icon={faUser}
							style={{ fontSize: 29, color: "white" }}
						/>
					</div>
				</div>                 */}

        <div className={`${styles["canvas"]} offcanvas offcanvas-start w-25`} data-bs-scroll="true" data-bs-backdrop="false" tabindex="-1" id="offcanvasScrolling" aria-labelledby="offcanvasScrollingLabel">
          <div className={`${styles["canvas-header"]} offcanvas-header `}>
            <Sidebar />
            <button class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
          </div>
        </div>
      </main>
    </div>
  );
}
