import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "/styles/Cdashboard.module.css";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faBars, faEnvelope, faUser } from "@fortawesome/free-solid-svg-icons";

export default function Employee() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Company Name</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.header}>
          <FontAwesomeIcon
            className={styles.icon}
            icon={faBars}
            style={{ fontSize: 32, color: "white" }}
          />
          <div className={styles.logo}>
            <Image
              src="/EasyHandler_Hitam.png"
              alt="logo"
              width={50}
              height={50}
            />
          </div>
          <div className={styles.headerRight}>
            <FontAwesomeIcon
              className={styles.icon2}
              icon={faEnvelope}
              style={{ fontSize: 29, color: "white" }}
            />
            <FontAwesomeIcon
              className={styles.icon2}
              icon={faUser}
              style={{ fontSize: 29, color: "white" }}
            />
          </div>
        </div>

        <div className={styles.content}>
            <Link href="/Company/edit">
              <a className={styles.editBut}>Edit</a>
            </Link>
          <div className={styles.left}>
            <div className={styles.formLogin}>
              <label>Company Name</label>
              <input name="name" type="text"></input>
            </div>

            <div className={styles.formLogin}>
              <label>Company Address</label>
              <input name="address" type="text"></input>
            </div>

            <div className={styles.formLogin}>
              <label>PIC Email</label>
              <input name="name" type="text"></input>
            </div>

            <div className={styles.formLogin}>
              <label>Employee quota</label>
              <input name="name" type="text"></input>
            </div>

            <div className={styles.formLogin}>
              <label>Company Logo</label>
              <input name="name" type="text"></input>
            </div>
          </div>

          <div className={styles.right}>
            <div className={styles.formLogin}>
              <label>Company Email</label>
              <input name="email" type="text"></input>
            </div>

            <div className={styles.formLogin}>
              <label>Company Number</label>
              <input name="address" type="text"></input>
            </div>

            <div className={styles.formLogin}>
              <label>PIC Number</label>
              <input name="name" type="text"></input>
            </div>

            <div className={styles.formLogin}>
              <label>Password</label>
              <input name="password" type="password"></input>
            </div>
          </div>
            <Link href="#">
              <a className={styles.addBut}>Add Super Admin</a>
            </Link>
        </div>
        <footer>
          <div className={styles.footer}></div>
        </footer>
      </main>
    </div>
  );
}
