import Head from "next/head";
import { useState } from "react";
import Image from "next/image";
import Link from "next/link";
import styles from "/styles/CdashEdit.module.css";
import React from "react";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faBars,
  faEnvelope,
  faUser,
  faArrowRight,
} from "@fortawesome/free-solid-svg-icons";
import { Button, Modal } from "react-bootstrap";

export default function Employee(props) {
  const [show, setShow] = useState(false);
  const [show1, setShow1] = useState(false);

  return (
    <div className={styles.container}>
      <Head>
        <title>Company Name</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.header}>
          <FontAwesomeIcon
            className={styles.icon}
            icon={faBars}
            style={{ fontSize: 32, color: "white" }}
          />
          <div className={styles.logo}>
            <Image
              src="/EasyHandler_Hitam.png"
              alt="logo"
              width={50}
              height={50}
            />
          </div>
          <div className={styles.headerRight}>
            <FontAwesomeIcon
              className={styles.icon2}
              icon={faEnvelope}
              style={{ fontSize: 29, color: "white" }}
            />
            <FontAwesomeIcon
              className={styles.icon2}
              icon={faUser}
              style={{ fontSize: 29, color: "white" }}
            />
          </div>
        </div>
        <div className={styles.content}>
          <div className={styles.left}>
            <div className={styles.formLogin}>
              <label>Company Name</label>
              <input name="name" type="text" defaultValue="Akbar Yanto"></input>
            </div>

            <div className={styles.formLogin}>
              <label>Company Address</label>
              <input
                name="address"
                type="text"
                defaultValue="Akbar Yanto"
              ></input>
            </div>

            <div className={styles.formLogin}>
              <label>PIC Email</label>
              <input name="name" type="text" defaultValue="Akbar Yanto"></input>
            </div>

            <div className={styles.formLogin}>
              <label>Employee quota</label>
              <input name="name" type="text" defaultValue="Akbar Yanto"></input>
            </div>
          </div>
          <div className={styles.right}>
            <div className={styles.formLogin}>
              <label>Company Email</label>
              <input
                name="email"
                type="Email"
                defaultValue="Akbar Yanto"
              ></input>
            </div>

            <div className={styles.formLogin}>
              <label>Company Number</label>
              <input
                name="address"
                type="text"
                defaultValue="Akbar Yanto"
              ></input>
            </div>

            <div className={styles.formLogin}>
              <label>PIC Number</label>
              <input name="name" type="text" defaultValue="Akbar Yanto"></input>
            </div>
            <div className={styles.formLogin}>
              <label>Company Logo</label>
              <input name="name" type="" defaultValue="Akbar Yanto"></input>
            </div>
          </div>

          <Link href="/Company/dashboard">
            <a className={styles.cancelBut}>Cancel</a>
          </Link>
          <Link href="/Company/dashboard">
            <a className={styles.saveBut}>Save</a>
          </Link>

          <Button
            variant="primary"
            onClick={() => setShow(!show)}
            className={styles.changeBut}
          >
            Change Password
          </Button>

          <Modal
            {...props}
            centered
            show={show}
            onHide={() => setShow(!show)}
            backdrop="static"
            keyboard={false}
          >
            <Modal.Header closeButton></Modal.Header>
            <Modal.Body>
              <label className={styles.mLabel}>Verify Password</label>
              <input
                className={styles.verifPass}
                name="Verify Password"
                type="Password"
              ></input>
            </Modal.Body>
            <Modal.Footer>
              <Button
                className={styles.nextBut}
                variant="primary"
                onClick={() => {
                  setShow(!show);
                  setTimeout(() => {
                    setShow1(!show1);
                  }, 400);
                }}
              >
                Next
                <FontAwesomeIcon
                  className={styles.arrow}
                  icon={faArrowRight}
                  style={{ fontSize: 16, color: "white" }}
                />
              </Button>
            </Modal.Footer>
          </Modal>

          <Modal
            {...props}
            centered
            show={show1}
            onHide={() => setShow1(!show1)}
            backdrop="static"
            keyboard={false}
          >
            <Modal.Header closeButton></Modal.Header>
            <Modal.Body>
              <label className={styles.mLabel}>New Password</label>
              <input
                className={styles.verifPass}
                name="Verify Password"
                type="Password"
              ></input>

              <label className={styles.mLabel}>Confirm Password</label>
              <input
                className={styles.verifPass}
                name="Verify Password"
                type="Password"
              ></input>
            </Modal.Body>
            <Modal.Footer>
              <Button
                className={styles.nextBut}
                variant="primary"
                onClick={() => setShow1(!show1)}
              >
                Save
                <FontAwesomeIcon
                  className={styles.arrow}
                  icon={faArrowRight}
                  style={{ fontSize: 16, color: "white" }}
                />
              </Button>
            </Modal.Footer>
          </Modal>
        </div>
        <footer>
          <div className={styles.footer}></div>
        </footer>
      </main>
    </div>
  );
}
