import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "/styles/CdashEdit.module.css";
import React from "react";
import Popup from "reactjs-popup";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faBars, faEnvelope, faUser } from "@fortawesome/free-solid-svg-icons";

const Modal = () => (
  <Popup trigger={<button className={styles.changeBut}> Change password </button>} modal>
    <div className={styles.formLogin}>
                  <label>Verify Password</label>
                  <input name="name" type="password"></input>
                </div>
                <Link href="#">
                  <a className={styles.nextBut}>Next</a>
                </Link>
  </Popup>
);

export default function Employee() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Company Name</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.header}>
          <FontAwesomeIcon
            className={styles.icon}
            icon={faBars}
            style={{ fontSize: 32, color: "white" }}
          />
          <div className={styles.logo}>
            <Image
              src="/EasyHandler_Hitam.png"
              alt="logo"
              width={50}
              height={50}
            />
          </div>
          <div className={styles.headerRight}>
            <FontAwesomeIcon
              className={styles.icon2}
              icon={faEnvelope}
              style={{ fontSize: 29, color: "white" }}
            />
            <FontAwesomeIcon
              className={styles.icon2}
              icon={faUser}
              style={{ fontSize: 29, color: "white" }}
            />
          </div>
        </div>
        <div className={styles.content}>
          <div className={styles.left}>
            <div className={styles.formLogin}>
              <label>Company Name</label>
              <input name="name" type="text"></input>
            </div>

            <div className={styles.formLogin}>
              <label>Company Address</label>
              <input name="address" type="text"></input>
            </div>

            <div className={styles.formLogin}>
              <label>PIC Email</label>
              <input name="name" type="text"></input>
            </div>

            <div className={styles.formLogin}>
              <label>Employee quota</label>
              <input name="name" type="text"></input>
            </div>
          </div>
          <div className={styles.right}>
            <div className={styles.formLogin}>
              <label>Company Email</label>
              <input name="email" type="Email"></input>
            </div>

            <div className={styles.formLogin}>
              <label>Company Number</label>
              <input name="address" type="text"></input>
            </div>

            <div className={styles.formLogin}>
              <label>PIC Number</label>
              <input name="name" type="text"></input>
            </div>
            <div className={styles.formLogin}>
              <label>Company Logo</label>
              <input name="name" type=""></input>
            </div>
          </div>

          <Link href="#">
            <a className={styles.cancelBut}>Cancel</a>
          </Link>
          <Link href="#">
            <a className={styles.saveBut}>Save</a>
          </Link>
        </div>
        <footer>
          <div className={styles.footer}></div>
        </footer>
      </main>
    </div>
  );
}
