import Head from "next/head";
import Image from "next/image";
import styles from "/styles/forgot.module.css";
import Link from "next/link";

export default function ForgotPass() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Company Name</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.wrapper}>
          <div className={styles.forgot}>
            <div className={styles.logo}>
              <Image
                src="/EasyHandler_Putih.png"
                alt="logo"
                width={150}
                height={150}
              />
            </div>
            <h2>Forgot Your Password?</h2>
            <p>Enter your email address and we'll send you a link to reset your password</p>
            <div className={styles.formForgot}>
              <label>Email</label>
              <input Email="Email" type="email"></input>
            </div>
            <Link href="newPass">
            <a className={styles.butSend}>Send</a> 
            </Link>
          </div>
          <div className={styles.logoForgot}>
          <Image
                src="/confused.png"
                alt="logo"
                width={250}
                height={250}
              />

          </div>
        </div>
      </main>
    </div>
  );
}
