import Head from "next/head";
import Image from "next/image";
import styles from "/styles/CsignUp.module.css";
import Link from "next/link";


export default function Signup() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Company Name</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.wrapper}>
          <div className={styles.signUp}>
            <div className={styles.logo}>
              <Image
                src="/EasyHandler_Putih.png"
                alt="logo"
                width={150}
                height={150}
              />
            </div>
            <h2>Create Your Account</h2>
            <div className={styles.formLogin}>
              <label>Company Name</label>
              <input name="name" type="text"></input>
            </div>

            <div className={styles.formLogin}>
              <label>Company Email</label>
              <input name="email" type="email"></input>
            </div>

            <div className={styles.formLogin}>
              <label>Company Number</label>
              <input name="Phone" type="text" ></input>
            </div>

            <div className={styles.formLogin}>
              <label>Company Address</label>
              <input name="address" type="address"></input>
            </div>

            <div className={styles.formLogin}>
              <label>Password</label>
              <input name="password" type="password"></input>
            </div>

            <div className={styles.formLogin}>
              <label>Confirm Password</label>
              <input name="Cpassword" type="password"></input>
            </div>
            <Link href="/Company/signUp2">
              <a className={styles.butSignup}>Next</a>
            </Link>
          </div>

          <div className={styles.signIn}>
            <p>Already have an account?</p>
            <Link href="/">
              <a className={styles.butSignin}>Sign In</a>
            </Link>
          </div>
        </div>
      </main>
    </div>
  );
}
