import Head from "next/head";
import Image from "next/image";
import styles from "/styles/newPass.module.css";
import Link from "next/link";

export default function NewPass() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Company Name</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.wrapper}>
          <div className={styles.forgot}>
            <div className={styles.logo}>
              <Image
                src="/EasyHandler_Putih.png"
                alt="logo"
                width={150}
                height={150}
              />
            </div>
            <h2>Create New Password</h2>
            <p>Your new password must be different from previous passwords</p>

            <div className={styles.formReset}>
              <label>Password</label>
              <input name="password" type="password"></input>
            </div>

            <div className={styles.formReset}>
              <label>Confirm Password</label>
              <input name="Cpassword" type="password"></input>
            </div>
            <Link href="/">
              <a className={styles.butReset}>Reset Password</a>
            </Link>
          </div>
          <div className={styles.logoForgot}>
          <Image
                src="/confused.png"
                alt="logo"
                width={250}
                height={250}
              />
          </div>
        </div>
      </main>
    </div>
  );
}
