import React from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "/styles/Dashboard.module.css";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faA, faBars, faBuilding, faCaretRight, faCircleInfo, faEnvelope, faMoneyBillTransfer, faSignal, faUser, faUserPlus } from "@fortawesome/free-solid-svg-icons";
import EDashboard from "./Edashboard";

export default function Dashboard() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Company Name</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.header}>
          <FontAwesomeIcon className={styles.icon} icon={faBars} style={{ fontSize: 32, color: "white" }} />
          <div className={styles.logo}>
            <Image src="/EasyHandler_Hitam.png" alt="logo" width={50} height={50} />
          </div>
          <div className={styles.headerRight}>
            <FontAwesomeIcon className={styles.icon2} icon={faEnvelope} style={{ fontSize: 29, color: "white" }} />
            <FontAwesomeIcon className={styles.icon2} icon={faUser} style={{ fontSize: 29, color: "white" }} />
          </div>
        </div>

        {/* <EDashboard /> */}

        <div className={styles.content}></div>

        <div className={styles.content}>
          <div className={styles.contentHead}>
            <h3>PT Hexaon Business Mitrasindo</h3>
            <p>good afternoon, ester!</p>
            <p className={styles.text}>it's thursday 19 may 2022</p>
          </div>

          <div className={styles.buttonHead}>
            <h4>Shortcut</h4>
            <ul>
              <li>
                <a href="#">Live Attendance</a>
              </li>
              <li>
                <a href="#">Request Reimbursement</a>
              </li>
              <li>
                <a href="#">Request Time Off</a>
              </li>
              <li>
                <a href="#">More Request</a>
              </li>
            </ul>
          </div>
        </div>

        <div className={styles.card1}>
          <h3>Employment Status</h3>
          <div className="parcial">
            <div className="info">
              <div className="percentageNum"></div>
            </div>
          </div>
        </div>

        <div className={styles.card2}>
          <h3>Gender Diversity</h3>
        </div>

        <div className={styles.card3}>
          <ul>
            <li>
              <a href="#">Announcement</a>
            </li>
            <li>
              <a href="#">Contract & Probation</a>
            </li>
            <li>
              <a href="#">Tasks</a>
            </li>
            <li>
              <a href="#">Polings</a>
            </li>
          </ul>
          <hr />
        </div>

        <div className={styles.card4}></div>

        <div className={styles.card5}>
          <div className={styles.quickl}>
            <h5>Quick Link</h5>
            <ul>
              <li>
                <a href="#">
                  <FontAwesomeIcon className={styles.icon} icon={faCircleInfo} styles={{ fontSize: "10", color: "black" }} />
                  My Info
                </a>
              </li>
              <li>
                <a href="#">
                  <FontAwesomeIcon className={styles.icon} icon={faUserPlus} styles={{ fontSize: "10", color: "black" }} />
                  Add Employee
                </a>
              </li>
              <li>
                <a href="#">
                  <FontAwesomeIcon className={styles.icon} icon={faMoneyBillTransfer} styles={{ fontSize: "10", color: "black" }} />
                  Employee Transfer
                </a>
              </li>
              <li>
                <a href="#">
                  <FontAwesomeIcon className={styles.icon} icon={faBuilding} styles={{ fontSize: "10", color: "black" }} />
                  Company Setting
                </a>
              </li>
            </ul>

            <div className={styles.app}>
              <h5>Application</h5>
              <ul>
                <li><a href="#"><FontAwesomeIcon className={styles.icon} icon={faSignal} styles={{ fontSize: "10", color: "black" }} />Performance Review</a></li>
              </ul>
            </div>

            <div className={styles.dezhl}>
              <h5>Download EZHL</h5>
              <ul>
                <li><a href="#"><FontAwesomeIcon className={styles.icon} icon={faA} styles={{ fontSize: "10", color: "black" }} />App Store</a></li>
                <li><a href="#"><FontAwesomeIcon className={styles.icon} icon={faCaretRight} styles={{ fontSize: "10", color: "black" }} />Google Play</a></li>
              </ul>
            </div>
          </div>
        </div>

        <div className={styles.card6}></div>

        <div className={styles.card7}></div>

        <div className={styles.card8}>
          <h3>Job Level</h3>
        </div>

        <div className={styles.card9}>
          <h3>Length Of Sevice</h3>
        </div>

        <footer>
          <div className={styles.footer}></div>
        </footer>
      </main>
    </div>
  );
}