import React from 'react'
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "/styles/Edashboard.module.css";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faBank, faBars, faBuilding, faBuildingColumns, faBuildingLock, faCalendar, faCalendarAlt, faCalendarCheck, faCalendarDay, faCalendarDays, faCalendarTimes, faEnvelope, faHome, faIdCard, faIdCardAlt, faMoneyBill, faSdCard, faTimesSquare, faUser, faUserAlt, faUserAltSlash, faUserCheck, faUsersBetweenLines } from "@fortawesome/free-solid-svg-icons";



export default function Dashboard() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Company Name</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.header}>
          <div className={styles.wrapper}>
           <div className={styles.Sidebar}>
            
               <a href="#" class="active">
                <FontAwesomeIcon
                className={styles.icon}
                icon={faHome}
                style={{ fontSize: "18", color: "black" }}
                />
                <span class="item">Dashboard</span>
                </a>
                <ul> 
                  <li><a href="#">Employees</a></li>
                </ul>
                
              <a href="#">
              <FontAwesomeIcon
                className={styles.icon}
                icon={faCalendarDays}
                style={{ fontSize: "18", color: "black" }}
                />
                <span class="item">Time Management</span>
                </a>
                <ul>
                  <li><a href="#">Time Off</a></li>
                  <li><a href="#">Attendance</a></li>
                  <li><a href="#">Schedule</a></li>
                  <li><a href="#">Calender</a></li>
                  <li><a href="#">Timesheet</a></li>
                </ul>

              <a href="#">
              <FontAwesomeIcon
                className={styles.icon}
                icon={faUserCheck}
                style={{ fontSize: "18", color: "black" }}
                />
              <span class="item">Finance</span>
                </a>
                <ul>
                  <li><a href="#">Reimbursement</a></li>
                  <li><a href="#">Cash Advance</a></li>
                  <li><a href="#">Loan</a></li>
                </ul>
                
              <a href="#">
              <FontAwesomeIcon
                className={styles.icon}
                icon={faMoneyBill}
                style={{ fontSize: "18", color: "black" }}
                />
              <span class="item">Payroll</span>
              </a>
              
              <a href="#">
              <FontAwesomeIcon
                className={styles.icon}
                icon={faBuilding}
                style={{ fontSize: "18", color: "black" }}
                />
              <span class="item">Company</span>
              </a>
           </div>
           <div class="section">
            <div class="top_navbar">
              <div class="hamburger">
                <a href="#">
                  <FontAwesomeIcon
                  className={styles.icon3}
                  icon={faBars}
                  style={{ fontSize: "30", color: "white" }}
                  />
                  </a>
              </div>
            </div>
           </div>
          </div>

          <div className={styles.logo}>
            <Image
              src="/EasyHandler_Hitam.png"
              alt="logo"
              width={50}
              height={50}
            />
          </div>
          
          <div className={styles.headerRight}>
            <FontAwesomeIcon
              className={styles.icon2}
              icon={faEnvelope}
              style={{ fontSize: 29, color: "white" }}
            />
            <FontAwesomeIcon
              className={styles.icon2}
              icon={faUser}
              style={{ fontSize: 29, color: "white" }}
            />
          </div>
        </div>
        <footer>
          <div className={styles.footer}></div>
        </footer>
      </main>
    </div>


  )
}