import React from 'react'
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "/styles/Edashboard.module.css";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faBars, faBuilding, faCalendarDays, faEnvelope, faHome, faMoneyBillTransfer, faPallet, faUser } from "@fortawesome/free-solid-svg-icons";
import Dashboard from './dashboard';


export default function EDashboard() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Company Name</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.backdrop}></div>
        <div className={styles.header}>
          <FontAwesomeIcon
            className={styles.icon} 
            icon={faBars}
            style={{ fontSize: 32, color: "white" }}
          />

          <div className={styles.logo}>
            <Image
              src="/EasyHandler_Hitam.png"
              alt="logo"
              width={50}
              height={50}
            />
          </div>

          <div className={styles.headerRight}>
            <FontAwesomeIcon
              className={styles.icon2}
              icon={faEnvelope}
              style={{ fontSize: 29, color: "white" }}
            />
            <FontAwesomeIcon
              className={styles.icon2}
              icon={faUser}
              style={{ fontSize: 29, color: "white" }}
            />
          </div>
        </div>

        <div className={styles.sidebar}>
        <li><FontAwesomeIcon
        className={styles.icon3}
        icon={faHome}/>Dashboard</li>
        <div className={styles.dropdown1}>
        <li><a href="#">Employees</a></li>
        </div>
        <li><FontAwesomeIcon
        className={styles.icon3}
        icon={faCalendarDays}/>Time Management</li>
        <div className={styles.dropdown2}>
            <li><a href="#">Time Off</a></li>
            <li><a href="#">Attendance</a></li>
            <li><a href="#">Schedule</a></li>
            <li><a href="#">Calender</a></li>
            <li><a href="#">Timesheet</a></li>
        </div>
        <li><FontAwesomeIcon
        className={styles.icon3}
        icon={faUser}/>Finance</li>
        <div className={styles.dropdown3}>
        <li><a href="#">Reimbursement</a></li>
        <li><a href="#">Cash Advance</a></li>
        <li><a href="#">Loan</a></li>
        </div>
        <li><FontAwesomeIcon
        className={styles.icon3}
        icon={faMoneyBillTransfer}/>Payroll</li>
        <li><FontAwesomeIcon
        className={styles.icon3}
        icon={faBuilding}/>Company</li>
        </div>

        <Dashboard /> 

        <footer>
          <div className={styles.footer}></div>
        </footer>
      </main>
    </div>
  )
}