import React from 'react'
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "/styles/ReprimandList.module.css";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faBars, faEnvelope, faUser, faMagnifyingGlass } from "@fortawesome/free-solid-svg-icons";


export default function ReprimandList() {
    return (
      <div className={styles.container}>
        <Head>
          <title>Company Name</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous"></link>
        </Head>
  
        <main className={styles.main}>
          <div className={styles.header}>
            <FontAwesomeIcon
              className={styles.icon}
              icon={faBars}
              style={{ fontSize: 32, color: "white" }}
            />
            <div className={styles.logo}>
              <Image
                src="/EasyHandler_Hitam.png"
                alt="logo"
                width={50}
                height={50}
              />
            </div>
            <div className={styles.headerRight}>
              <FontAwesomeIcon
                className={styles.icon2}
                icon={faEnvelope}
                style={{ fontSize: 29, color: "white" }}
              />
             <div className={styles.image2}>
             <img src="/Group_3.png" className={styles.image2}></img>
             </div>
            </div>
          </div>
          <div className={styles.image}>
            <img src="/image_535.png" className={styles.image}></img>
          </div>
          <div className={styles.box}>
            <div className={styles.link}>
              <a>Reprimand List</a>
              <a>Reprimand Type</a>
            </div>
            <div className={styles.content}> 
            <div class="d-flex justify-content-between align-items-center">
              <button type="button" class="btn btn-outline-secondary btn-sm mt-4 ms-4 mb-3">ADD NEW</button>
              <button type="button" class="btn btn-outline-secondary btn-sm mt-4 me-4 mb-3">FILTER</button>
            </div>
            <section class="section-sellect-search mb-4">
              <div class="container-fluid">
                <div class="row mt-3 justify-content-end me-1">
                  <div class="col-1">
                    <label for="select" className={`${styles.formLabel} form-label`}>
                      Showing
                    </label>
                    <select className={`${styles.formSelect} form-select`} id="select">
                      <option selected>10</option>
                      <option value="25">25</option>
                      <option value="50">50</option>
                      <option value="75">75</option>
                      <option value="100">100</option>
                    </select>
                  </div>
                  <div class="col-2">
                    <label for="search" className={`${styles.formLabel} form-label`}>
                      Search
                    </label>
                    <div className={`input-group mb-3`}>
                      <span className={`${styles.spanIcon} input-group-text`}>
                        <FontAwesomeIcon className={styles.searchIcon} icon={faMagnifyingGlass} />
                      </span>
                      <input type="text" className={`${styles.searchInput} form-control`}></input>
                    </div>
                  </div>
                </div>
              </div>
            </section>
            <table class="table mt-2">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">First</th>
      <th scope="col">Last</th>
      <th scope="col">Handle</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>Mark</td>
      <td>Otto</td>
      <td>@mdo</td>
    </tr>
  </tbody>
</table>
            </div>
          </div>
        </main>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
      </div>
    )
}