import React, { useEffect, useRef, useState } from "react";
import Head from "next/head";
import styles from "/styles/Announcement/AddNew.module.css";

const AddNewAnnouncement = ({
  closeModal,
  name,
  value,
}) => {
  const editorRef = useRef();
  const [editorLoaded, setEditorLoaded] = useState(false);
  const { CKEditor, ClassicEditor } = editorRef.current || {};

  useEffect(() => {
    setEditorLoaded(true)
    editorRef.current = {
      CKEditor: require("@ckeditor/ckeditor5-react").CKEditor, // v3+
      ClassicEditor: require("@ckeditor/ckeditor5-build-classic"),
    };
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Company Name</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx"
          crossorigin="anonymous"
        ></link>

        <script
          src="https://cdn.tiny.cloud/1/no-api-key/tinymce/6/tinymce.min.js"
          referrerpolicy="origin"
        ></script>
      </Head>

      <main className={styles.main}>
        <div className={`${styles.modal} modal-content rounded-0`}>
          <div
            className={`${styles.modalContent} modal-header mt-2 ms-3 mb-3 me-3`}
          >
            <h3 class="modal-title">Add Announcement</h3>
          </div>
          <div class="modal-body ms-3">
          <div class="d-flex justify-content-between">
            <div class="col-12">
              <label for="subject" className={`${styles.formLabel} form-label`}>
                Subject
              </label>
              <div className={`input-group mb-4`}>
                <input type="text" id="subject" className={`${styles.inputsubject} form-control`}></input>
              </div>
            </div>
            </div>

          <h6>Content</h6>
          {editorLoaded ? (
            <CKEditor
              type=""
              name={name}
              editor={ClassicEditor}
              data={value}
              onChange={(event, editor) => {
                const data = editor.getData();
                // onChange(data);
              }}
            />
            ) : (
              <div>Editor loading</div>
            )}
          </div>
          <div class="modal-footer border-top mb-2">
            <button
              type="button"
              className={`${styles.btnModal} btn btn-outline-secondary mt-2 me-1 btn-sm`}
              onClick={() => closeModal(false)}
            >
              CREATE ANNOUNCEMENT
            </button>
            <button
              type="button"
              className={`${styles.btnModal} btn btn-outline-secondary mt-2 me-2 btn-sm`}
              data-bs-dismiss="modal"
            >
              CANCEL
            </button>
          </div>
        </div>
      </main>

      <script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
        crossorigin="anonymous"
      ></script>
    </div>
  );
};

export default AddNewAnnouncement;
